#!/usr/bin/env bash

# Added by Toolbox App
export PATH="${HOME}.local/share/JetBrains/Toolbox/scripts:${PATH}"

if [ -f "${HOME}/.bashrc" ]; then
  # shellcheck disable=SC1091
  source "${HOME}/.bashrc"
fi
