#!/usr/bin/env bash
# -*-mode:bash-*- vim:ft=bash
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

# User specific environment
# shellcheck disable=SC2076
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
  PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
#export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d "${HOME}/.bashrc.d" ]; then
  for rc in "${HOME}/.bashrc.d/"*; do
    if [ -f "$rc" ]; then
      # shellcheck disable=SC1090
      source "$rc"
    fi
  done
fi

unset rc
