---
name: Lint
'on':
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: go install github.com/google/yamlfmt/cmd/yamlfmt@latest
      - uses: actions/checkout@v3
      - name: pre-commit
        uses: pre-commit/action@v3.0.0
