---
name: CI
'on':
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go Environment
        uses: actions/setup-go@v5.0.0
        with:
          cache: true
      - run: go install github.com/google/yamlfmt/cmd/yamlfmt@latest
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
